version: '3'
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: raw_office
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: notsecret
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ./new-database:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    networks:
      - backend
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: raw_office
      DB_USERNAME: laravel_user
      DB_PASSWORD: notsecret

  nginx:
    image: nginx:mainline-alpine
    networks:
      - backend
    ports:
      - '8080:8080'
    restart: on-failure
    volumes:
      - .:/var/www/html
      - ./nginx_config.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    depends_on:
      - php

volumes:
  new-database: {}

networks:
    backend:
        driver: bridge
